`define GVIO0_DEF_PROBE_OUT0
`define GVIO0_DEF_PROBE_OUT1
`define GVIO0_DEF_PROBE_OUT2
`define GVIO0_DEF_PROBE_OUT3
`define GVIO0_DEF_PROBE_OUT4
`define GVIO0_DEF_PROBE_OUT5
`define GVIO0_DEF_PROBE_OUT6
`define GVIO0_DEF_PROBE_OUT_SYNC
