-d /Users/serg/robot/robot/gowin/TangPrimer-25K-example/pmod_digitalTube-2bit/impl/gwsynthesis/pmod_digitalTube-2bit.vg
-p GW5A-25A-MBGA121N-1
-pn GW5A-LV25MG121NC1/I0
-cst /Users/serg/robot/robot/gowin/TangPrimer-25K-example/pmod_digitalTube-2bit/src/pmod_digitalTube-2bit.cst
-cfg /Users/serg/robot/robot/gowin/TangPrimer-25K-example/pmod_digitalTube-2bit/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
-enable_dsrm 0
